spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: 0oa15vok33BJ6iuoZ357
            client-secret: w4tKCHcqRaY4sozkFawLFkuGSgHSnX6Xfi89GTUU
            scope: openid, email, profile
        provider:
          okta:
            issuer-uri: https://dev-738205.okta.com/oauth2/default